"""initial migration

Revision ID: 587b11258681
Revises: 
Create Date: 2018-09-02 11:09:29.970719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587b11258681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageseval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imagename', sa.String(length=255), nullable=False),
    sa.Column('good', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.Column('poor', sa.Integer(), nullable=True),
    sa.Column('eval', sa.Text(), nullable=True),
    sa.Column('eval_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagesinfodf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imgindex', sa.Integer(), nullable=True),
    sa.Column('imagename', sa.Text(), nullable=True),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagesinfodf')
    op.drop_table('imageseval')
    # ### end Alembic commands ###
